### ISSUE TITLE
Some information about the library usage

### ISSUE THREAD

**Issue by RajS999** [rystrauss/interact#7]
Can we use these implementations of agents in non-gaming environments? That is mainly when state or observation space is not game frames but say lists. I am looking for simpler PPG implementation for such list-based state space. The possible issue is to have simple feed forward neural network based policy instead of CNN based policy. 

Just for comparison, I guess, in stable-baselines3, `MlpPolicy` is used as policy for such cases, unlike `CnnPolicy` which is required for gaming environments observation / state space. But stable-baselines3 does not have PPG implementation.

Also are all these implementations tensorflow based or pytorch based. I was going through the code for some days. I guess somewhere I read both, but not able to find now where did I read that. So started guessing if I mis-read. 

PS: sorry, I feel raising issue is incorrect way to ask for information

**Comment by rystrauss** [comment]
@RajS999 Yes, this implementation should work with almost any Gym environment. By default pretty much all of the algorithms, including PPG, default to an MLP network, not a CNN (`PPG.policy_network = "mlp"` by default). So you can certainly run PPG with an environment that has list-like observations (as opposed to images), and they will be processed by a feed-forward network ([here](https://github.com/rystrauss/interact/blob/4fd8a5ffd2b712beb81bc43587745b29c715d754/interact/networks.py#L47) is the function that builds that network).

And this package is written entirely in TensorFlow.

**Comment by rystrauss** [comment]
Closing this issue. [Discussions](https://github.com/rystrauss/interact/discussions) is a better place for questions.
